env:
  global:
    - LC_CTYPE=en_US.UTF-8

branches:
  only:
    - master

matrix:
  include:
    - os: osx
      osx_image: xcode12
      language: objective-c
      env:
        - JOB=Xcode
      script:
        - set -o pipefail
        - xcodebuild build-for-testing test-without-building -workspace JSONRPCKit.xcworkspace -scheme JSONRPCKit -configuration Release ENABLE_TESTABILITY=YES | xcpretty -c
        - xcodebuild build-for-testing test-without-building -workspace JSONRPCKit.xcworkspace -scheme JSONRPCKit -configuration Release -sdk iphonesimulator -destination "name=iPhone 8" ENABLE_TESTABILITY=YES | xcpretty -c
        - xcodebuild build-for-testing test-without-building -workspace JSONRPCKit.xcworkspace -scheme JSONRPCKit -configuration Release -sdk appletvsimulator -destination "name=Apple TV" ENABLE_TESTABILITY=YES | xcpretty -c
        - xcodebuild build -workspace JSONRPCKit.xcworkspace -scheme JSONRPCKit -sdk watchsimulator | xcpretty -c
    - os: osx
      osx_image: xcode12
      language: generic
      env:
        - JOB=SPM
      script:
        - swift --version
        - swift build
        - swift test
    - os: linux
      language: generic
      env:
        - JOB=Linux
        - SWIFT_VERSION=5.3
      script:
        - swift --version
        - swift build
        - swift test
      sudo: required
      dist: trusty
      install:
        - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"

notifications:
  email: false
